services:
  backend_service:
    build: .
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    depends_on:
      - postgres_service
      - redis_service
      - minio_service
    volumes:
      - .:/app

  postgres_service:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=1
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis_service:
    image: redis:alpine
    ports:
      - "6379:6379"

  minio_service:
    image: minio/minio:latest
    ports:
      - "9000:9000"     # API
      - "9001:9001"     # Web console
    env_file:
      - .env.prod
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  pg_data:
  minio-data:


