# Generated by Django 5.2.7 on 2025-10-13 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarType',
            new_name='CarCategory',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='type',
            new_name='category',
        ),
    ]
